# Generated by Django 5.2.6 on 2025-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsalesdetails',
            name='token',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
