# Generated by Django 5.2.6 on 2025-10-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_retailsalesdetails_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsalesdetails',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
