# Generated by Django 5.2.6 on 2025-10-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_retailsalesdetails_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=20, unique=True)),
                ('sales_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('delete_status', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash'), ('online', 'Online')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_sales_added', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_sales_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_sales_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleSalesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.wholesalesales')),
            ],
        ),
    ]
