# Generated by Django 5.2.4 on 2025-10-31 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wholesalesales_wholesalesalesdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplierpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supplier')),
            ],
        ),
    ]
