# Generated by Django 5.2.4 on 2025-10-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_supplierpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpay',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='supplierpay',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier'),
            preserve_default=False,
        ),
    ]
