# Generated by Django 5.2.4 on 2025-10-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_supplierpay_supplier_id_supplierpay_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpay',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
