# Generated by Django 5.2.4 on 2025-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salary_per_day',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
