# Generated by Django 5.2.4 on 2025-11-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsales',
            name='take_amay_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.employe'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin')], default='staff', max_length=20),
        ),
    ]
