# Generated by Django 5.2.4 on 2025-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_retailsales_take_amay_employee_alter_employe_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='alias',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('pending', 'Pending')], default='cash', max_length=20),
        ),
    ]
