# Generated by Django 5.2.4 on 2025-11-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_branch_alias_alter_retailsales_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpay',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
    ]
