# Generated by Django 5.2.4 on 2025-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_supplierpay_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='no_of_boxes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
