# Generated by Django 5.2.4 on 2025-12-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_purchasedetail_no_of_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsales',
            name='round_off',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='empty_weight',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=12),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='retailsalesdetails',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='retailsalesdetails',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='retailsalesdetails',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=5),
        ),
        migrations.AlterField(
            model_name='retailsalesdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=12),
        ),
        migrations.AlterField(
            model_name='wholesalesales',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wholesalesales',
            name='payment_mode',
            field=models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash'), ('online', 'Online')], default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='wholesalesalesdetails',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wholesalesalesdetails',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wholesalesalesdetails',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=5),
        ),
        migrations.AlterField(
            model_name='wholesalesalesdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=12),
        ),
    ]
