# Generated by Django 5.2.4 on 2025-12-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_retailsales_round_off_alter_purchase_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='whole_sale',
            field=models.BooleanField(default=False),
        ),
    ]
