# Generated by Django 5.2.4 on 2025-12-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customer_delete_status_customer_whole_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='receipt_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='wholesalesales',
            name='receipt_no',
            field=models.CharField(max_length=20),
        ),
    ]
