# Generated by Django 5.2.4 on 2025-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customer_gstin_alter_retailsales_receipt_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsales',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online'), ('pending', 'Pending')], default='cash', max_length=20),
        ),
    ]
