# Generated by Django 5.2.4 on 2025-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_wholesalepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailsales',
            old_name='round_off',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='retailsales',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wholesalesales',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wholesalesales',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
