# Generated by Django 5.2.4 on 2026-01-13 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_expense_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='wastageValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastage', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
            ],
        ),
    ]
