# Generated by Django 5.2.4 on 2026-01-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_wastagevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeild_percentage', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('multipler', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
            ],
        ),
        migrations.DeleteModel(
            name='wastageValues',
        ),
    ]
