# Generated by Django 5.2.4 on 2026-01-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_yieldpercentage_delete_wastagevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailystockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('purchase_stock', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('total_stock', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('sales', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('live_weight', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('closing_stock', models.DecimalField(decimal_places=3, default='0.000', max_digits=12)),
                ('updated_date', models.DateField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item')),
            ],
        ),
    ]
