# Generated by Django 5.2.4 on 2026-01-14 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_dailystockupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailystockupdate',
            options={'ordering': ['-date', 'item__name']},
        ),
        migrations.RenameField(
            model_name='dailystockupdate',
            old_name='updated_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='dailystockupdate',
            unique_together={('item', 'date', 'branch')},
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_weight_closing',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_weight_derived',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='todays_sales',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailystockupdate',
            name='closing_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailystockupdate',
            name='opening_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailystockupdate',
            name='purchase_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailystockupdate',
            name='total_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='dailystockupdate',
            name='live_weight',
        ),
        migrations.RemoveField(
            model_name='dailystockupdate',
            name='sales',
        ),
    ]
