# Generated by Django 5.2.4 on 2026-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_dailystockupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
