# Generated by Django 5.2.4 on 2026-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_item_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='include_in_stock_update',
            field=models.BooleanField(default=False),
        ),
    ]
