# Generated by Django 5.2.4 on 2026-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_itemcategory_include_in_stock_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, default='0.000', max_digits=10),
        ),
    ]
