# Generated by Django 5.2.4 on 2026-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customer_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalesales',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
