# Generated by Django 5.2.4 on 2026-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_wholesalesales_pending_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(blank=True, null=True),
        ),
    ]
