# Generated by Django 5.2.4 on 2026-02-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_supplier_email_alter_supplier_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsales',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
