# Generated by Django 5.2.4 on 2026-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_retailsales_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsales',
            name='total_card',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='retailsales',
            name='total_cash',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='retailsales',
            name='total_upi',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='retailsales',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('multiple', 'Multiple'), ('pending', 'Pending')], default='cash', max_length=20),
        ),
    ]
