# Generated by Django 5.2.4 on 2026-02-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_retailsales_total_card_retailsales_total_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailsales',
            old_name='paid_amount',
            new_name='pending_amount',
        ),
    ]
