# Generated by Django 5.2.4 on 2026-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_rename_paid_amount_retailsales_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_address_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
