# Generated by Django 5.2.4 on 2026-02-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_branch_branch_address_full_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalepayment',
            name='receipt_no',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
