# Generated by Django 5.2.4 on 2026-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_wholesalepayment_receipt_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailystockupdate',
            old_name='live_weight_derived',
            new_name='actual_stock',
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_opening_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_purchase_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_todays_sales',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_total_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='spoilage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='weight_loss',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
