# Generated by Django 5.2.4 on 2026-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_rename_live_weight_derived_dailystockupdate_actual_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_actual_stock',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_spoilage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailystockupdate',
            name='live_weight_loss',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
