# Generated by Django 5.2.4 on 2026-02-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_dailystockupdate_live_actual_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
