# Generated by Django 5.2.4 on 2026-03-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_expensecategory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
        ),
    ]
