# Generated by Django 5.2.4 on 2026-05-03 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_pettycashbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycashbalance',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=10000.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ItemBranchPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit_retail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_unit_wholesale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='accounts.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch__branch_name', 'item__name'],
                'unique_together': {('item', 'branch')},
            },
        ),
    ]
